
<html>
<head>
	<title>3beet-vip</title>
<link rel="icon" type="image/png" href="favicon-32x32.png" sizes="32x32" />
<link rel="icon" type="image/png" href="favicon-16x16.png" sizes="16x16" />

	<link rel="apple-touch-icon" sizes="76x76" href="favicon-32x32.png">
	
	<link rel="mask-icon" href="steve-jobs.svg" color="red">
	
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
<base target="_blank"/> 





<body class="pinstripe nolegacy">
<panel>
	
	<div align="center"> 
	
	<block>
		<p>مرحبا بك في سورس العبيط</p>
</block>
	
<block>
	<p>ادوات خفيفه ومهمة بعضها محذوفة</p>
	<p>ضيف لا افوتك</p>
	<p>ادوات اساسية</p>
	
</block>

<fieldset>
	<a href="cydia://url/https://cydia.saurik.com/api/share#?source= https://github.com/3beet-vip/repo/"><img src="./CydiaIcon.png" class="icon"><div><div><label><p>اضافة السورس للسيديا</p></label><label class="url"><p></p></label></div></div></a>
</fieldset>
<block>
	<p>الــدعم الفني</p>
</block>

<fieldset>
	<a href="mailto:shipani860@gmail.com"><img src="./opened-email-envelope.png" class="icon"><div><div><label><p>لمراسلتي</p></label></div></div></a>
</fieldset>

<block>
<a href="https://twitter.com/Cydiavip1">Twitter</a>
</block>



<footer> &copy; 2014 - 2017 Malr Rdd Inc. 

	 

	</div>
	
</panel>
</body>
</html>
